//! ABI bindings, generated by `build.rs` via `substreams_ethereum::Abigen`.
//!
//! Never hand-written. The source ABI JSON in `abi/` is itself produced by
//! `forge inspect` from the compiled contracts, so the decoding path is
//! generated end to end from the Solidity.

#[allow(clippy::all, dead_code, unused_imports)]
pub mod aqua;

#[allow(clippy::all, dead_code, unused_imports)]
pub mod zyro_router;
