import {BigInt} from "@graphprotocol/graph-ts";

/**
 * The Avellaneda–Stoikov pricing kernel, in AssemblyScript.
 *
 * A faithful re-implementation of `contracts/src/libs/AvellanedaStoikov.sol`,
 * and the reason this subgraph is worth deploying at all. Zyro's liquidity is
 * order-based and spread across individual makers — there is no pool contract
 * holding reserves, so a router cannot read a reserve to price a Zyro position.
 * It would have to re-derive this entire calculation itself. Running it here
 * means a solver can query the current reservation price directly.
 *
 * Checked against `contracts/test/fixtures/kernel.json`, which is generated by
 * a live run of the Solidity. See `tests/` — a subgraph that publishes a price
 * the chain would not quote is worse than one that publishes nothing.
 *
 * ## AssemblyScript caveats that bite here
 *
 * - `BigInt` division truncates toward zero, matching Solidity. The skew term
 *   is signed, so this is load-bearing.
 * - There is no operator overloading for comparison: use `.lt`, `.gt`, `.equals`
 *   rather than `<`, `>`, `==`.
 * - `BigInt.fromI32` is the only safe small-int constructor; literals are `i32`.
 */

export const WAD: BigInt = BigInt.fromString("1000000000000000000");
export const BPS: BigInt = BigInt.fromI32(10000);
export const MAX_PENALTY_BPS: BigInt = BigInt.fromI32(500);

export class Params {
  gammaWad: BigInt;
  sigmaSqWad: BigInt;
  baseSpreadWad: BigInt;
  horizonSecs: BigInt;

  constructor(
    gammaWad: BigInt,
    sigmaSqWad: BigInt,
    baseSpreadWad: BigInt,
    horizonSecs: BigInt
  ) {
    this.gammaWad = gammaWad;
    this.sigmaSqWad = sigmaSqWad;
    this.baseSpreadWad = baseSpreadWad;
    this.horizonSecs = horizonSecs;
  }
}

function abs(x: BigInt): BigInt {
  return x.lt(BigInt.zero()) ? x.neg() : x;
}

/**
 * Floor of the integer square root, matching OpenZeppelin's `Math.sqrt`.
 *
 * Newton's method can settle one above the true floor, so the loop condition
 * corrects for it. Getting this wrong shifts every re-centred balance by one
 * wei, which is small enough to look like rounding and never be investigated.
 */
export function sqrt(n: BigInt): BigInt {
  if (n.lt(BigInt.fromI32(2))) return n;

  let x = n;
  let y = x.plus(BigInt.fromI32(1)).div(BigInt.fromI32(2));
  while (y.lt(x)) {
    x = y;
    y = x.plus(n.div(x)).div(BigInt.fromI32(2));
  }
  return x;
}

/**
 * Seconds left in the quoting horizon, floored at zero.
 *
 * Once this hits zero every time-dependent term vanishes and the position
 * quietly becomes an ordinary constant-product AMM with a flat spread. It does
 * not revert or stop trading — it stops defending itself.
 */
export function remaining(p: Params, elapsed: BigInt): BigInt {
  return elapsed.ge(p.horizonSecs) ? BigInt.zero() : p.horizonSecs.minus(elapsed);
}

/** The shared risk term `gamma * sigmaSq * (T - t)`, in WAD. */
export function riskTermWad(p: Params, elapsed: BigInt): BigInt {
  let pressure = p.gammaWad.times(p.sigmaSqWad).div(WAD);
  return pressure.times(remaining(p, elapsed));
}

/** `r = s - q * gamma * sigmaSq * (T - t)`. */
export function reservationPriceWad(
  mid: BigInt,
  q: BigInt,
  p: Params,
  elapsed: BigInt
): BigInt {
  let skew = q.times(riskTermWad(p, elapsed)).div(WAD);
  return mid.minus(skew);
}

/** `delta = delta0 + gamma * sigmaSq * (T - t)`, an absolute WAD price offset. */
export function halfSpreadWad(p: Params, elapsed: BigInt): BigInt {
  let d = p.baseSpreadWad.plus(riskTermWad(p, elapsed));
  return d.lt(BigInt.zero()) ? BigInt.zero() : d;
}

/**
 * Penalty ramping linearly 0 → 500 bps as `|q|/|bound|` goes 0 → 1, then
 * clamping. Applied to exposed-side flow only.
 */
export function softBoundPenaltyBps(q: BigInt, bound: BigInt): BigInt {
  let absBound = abs(bound);
  if (absBound.isZero()) return BigInt.zero();

  let penalty = abs(q).times(MAX_PENALTY_BPS).div(absBound);
  return penalty.gt(MAX_PENALTY_BPS) ? MAX_PENALTY_BPS : penalty;
}

/** `s = balanceOut * WAD / balanceIn`, the price implied by the pair. */
export function midFromBalancesWad(balanceIn: BigInt, balanceOut: BigInt): BigInt {
  if (balanceIn.isZero()) return BigInt.zero();
  return balanceOut.times(WAD).div(balanceIn);
}

/**
 * The effective price this direction quotes: `r - delta` when exposed,
 * `r + delta` when covered, floored at 1.
 */
export function effectivePriceWad(
  mid: BigInt,
  q: BigInt,
  p: Params,
  elapsed: BigInt
): BigInt {
  let r = reservationPriceWad(mid, q, p, elapsed);
  let delta = halfSpreadWad(p, elapsed);
  let price = q.ge(BigInt.zero()) ? r.minus(delta) : r.plus(delta);
  return price.lt(BigInt.fromI32(1)) ? BigInt.fromI32(1) : price;
}

/**
 * Rotates the curve so its implied price becomes `price`, holding depth
 * `k = balanceIn * balanceOut` constant. Returns the inputs unchanged on a
 * degenerate price, matching the on-chain continuity rule.
 */
export function recenterBalances(
  balanceIn: BigInt,
  balanceOut: BigInt,
  price: BigInt
): BigInt[] {
  if (price.le(BigInt.zero())) return [balanceIn, balanceOut];

  let k = balanceIn.times(balanceOut);
  if (k.isZero()) return [balanceIn, balanceOut];

  let newBalanceIn = sqrt(k.times(WAD).div(price));
  if (newBalanceIn.isZero()) return [balanceIn, balanceOut];

  return [newBalanceIn, k.div(newBalanceIn)];
}

/** The whole mechanism, as one transform. Mirrors `applyInventorySkew`. */
export function applyInventorySkew(
  balanceIn: BigInt,
  balanceOut: BigInt,
  q: BigInt,
  p: Params,
  elapsed: BigInt,
  bound: BigInt
): BigInt[] {
  let mid = midFromBalancesWad(balanceIn, balanceOut);
  let price = effectivePriceWad(mid, q, p, elapsed);

  let pair = recenterBalances(balanceIn, balanceOut, price);
  let newIn = pair[0];
  let newOut = pair[1];

  if (q.ge(BigInt.zero())) {
    let penaltyBps = softBoundPenaltyBps(q, bound);
    if (!penaltyBps.isZero()) {
      newOut = newOut.minus(newOut.times(penaltyBps).div(BPS));
    }
  }

  return [newIn, newOut];
}
