import {Address} from "@graphprotocol/graph-ts";

/**
 * The Zyro router's address, as an Aqua "app".
 *
 * Aqua's `Shipped`, `Pushed`, `Pulled` and `Docked` fire for **every** app
 * built on Aqua, not just this one. Every handler filters on this address;
 * without it the subgraph would try to decode unrelated protocols' strategies
 * as Zyro programs and publish nonsense for them.
 *
 * `graph build --network <name>` substitutes contract addresses in
 * `subgraph.yaml` from `networks.json`, but it cannot substitute a constant in
 * mapping code — so this is set here per deployment.
 *
 * GENERATED by `node scripts/wire-addresses.mjs`. Editing it by hand is how it
 * falls out of step with `networks.json`, and a stale value does not error:
 * every event simply fails the filter and the subgraph syncs to chainhead in
 * perfect health having indexed nothing.
 */
export const ZYRO_APP: Address = Address.fromString(
  "0x915900ccc5409beb4d11b2c4bd4c7f94b2648335"
);
