/**
 * The Avellaneda–Stoikov pricing kernel, off-chain.
 *
 * A faithful re-implementation of `contracts/src/libs/AvellanedaStoikov.sol`.
 * It exists because Zyro's liquidity is order-based: there is no pool contract
 * holding reserves, so a solver cannot read a reserve to price a position — it
 * has to be *told* the reservation price, which means the kernel has to run
 * off-chain too.
 *
 * That makes divergence the central risk. A quote derived here that the chain
 * would not honour is worse than no quote at all: a solver routes on it and the
 * execution disagrees. So every function here is checked against reference
 * outputs generated by a live run of the Solidity
 * (`contracts/test/KernelFixtures.t.sol` → `test/fixtures/kernel.json`), and CI
 * fails if the two drift.
 *
 * ## Why the arithmetic lines up
 *
 * Solidity and JavaScript agree on the two things that matter here:
 *
 * - `BigInt` is arbitrary precision, so there is no silent overflow where
 *   `int256` would have one — the Solidity's own bounds (`validate`) are what
 *   keep values in range, and they are mirrored in `validateZyroParams`.
 * - Integer division **truncates toward zero** in both, including for negative
 *   operands. This is load-bearing: the skew term is signed, and a language
 *   that floored instead would be off by one on every negative result.
 */

const WAD = 10n ** 18n;
const BPS = 10_000n;
const MAX_PENALTY_BPS = 500n;

export interface KernelParams {
  gammaWad: bigint;
  sigmaSqWad: bigint;
  baseSpreadWad: bigint;
  horizonSecs: bigint;
}

/** Absolute value of a bigint. */
function abs(x: bigint): bigint {
  return x < 0n ? -x : x;
}

/**
 * Floor of the integer square root, matching OpenZeppelin's `Math.sqrt`.
 *
 * @throws on a negative input — the Solidity takes a `uint256`, so a negative
 *         value here means the caller has already gone wrong.
 */
export function sqrt(n: bigint): bigint {
  if (n < 0n) throw new Error(`sqrt of a negative value: ${n}`);
  if (n < 2n) return n;

  // Newton's method from a power-of-two seed, then a correction step, since
  // Newton can land one above the true floor.
  let x = n;
  let y = (x + 1n) / 2n;
  while (y < x) {
    x = y;
    y = (x + n / x) / 2n;
  }
  return x;
}

/**
 * Seconds left in the quoting horizon, floored at zero.
 *
 * Once this reaches zero every time-dependent term vanishes and the position
 * silently becomes an ordinary constant-product AMM with a flat spread. It does
 * not revert, warn, or stop trading — it stops defending itself.
 */
export function remaining(p: KernelParams, elapsed: bigint): bigint {
  return elapsed >= p.horizonSecs ? 0n : p.horizonSecs - elapsed;
}

/** The shared risk term `gamma * sigmaSq * (T - t)`, in WAD. */
export function riskTermWad(p: KernelParams, elapsed: bigint): bigint {
  const pressure = (p.gammaWad * p.sigmaSqWad) / WAD;
  return pressure * remaining(p, elapsed);
}

/** `r = s - q * gamma * sigmaSq * (T - t)`. */
export function reservationPriceWad(
  mid: bigint,
  q: bigint,
  p: KernelParams,
  elapsed: bigint,
): bigint {
  const skew = (q * riskTermWad(p, elapsed)) / WAD;
  return mid - skew;
}

/** `delta = delta0 + gamma * sigmaSq * (T - t)`, an absolute WAD price offset. */
export function halfSpreadWad(p: KernelParams, elapsed: bigint): bigint {
  const d = p.baseSpreadWad + riskTermWad(p, elapsed);
  return d < 0n ? 0n : d;
}

/**
 * Soft-bound penalty, ramping linearly 0 → 500 bps as `|q|/|bound|` goes 0 → 1,
 * then clamping.
 *
 * A hard revert at a boundary is a discontinuity, and discontinuities are
 * hostile to the automated solvers that route order flow: they receive a
 * successful quote and then a reverting execution.
 */
export function softBoundPenaltyBps(q: bigint, bound: bigint): bigint {
  const absBound = abs(bound);
  if (absBound === 0n) return 0n;
  const penalty = (abs(q) * MAX_PENALTY_BPS) / absBound;
  return penalty > MAX_PENALTY_BPS ? MAX_PENALTY_BPS : penalty;
}

/** `s = balanceOut * WAD / balanceIn`, the price implied by the pair. */
export function midFromBalancesWad(balanceIn: bigint, balanceOut: bigint): bigint {
  if (balanceIn === 0n) return 0n;
  return (balanceOut * WAD) / balanceIn;
}

/**
 * Rotates the curve so its implied price becomes `price`, holding depth
 * `k = balanceIn * balanceOut` constant.
 *
 * The curve is rotated, not reshaped — traders see the same depth, quoted
 * around `r` instead of raw mid. Returns the inputs unchanged on a degenerate
 * price rather than throwing, matching the Solidity's continuity rule.
 */
export function recenterBalances(
  balanceIn: bigint,
  balanceOut: bigint,
  price: bigint,
): [bigint, bigint] {
  if (price <= 0n) return [balanceIn, balanceOut];

  const k = balanceIn * balanceOut;
  if (k === 0n) return [balanceIn, balanceOut];

  const newBalanceIn = sqrt((k * WAD) / price);
  if (newBalanceIn === 0n) return [balanceIn, balanceOut];

  return [newBalanceIn, k / newBalanceIn];
}

/**
 * The whole mechanism, as one transform.
 *
 * The instruction always adds to `balanceIn` (the taker gives tokenIn), so the
 * sign of `q` alone decides which side of `r` this lands on.
 */
export function applyInventorySkew(
  balanceIn: bigint,
  balanceOut: bigint,
  q: bigint,
  p: KernelParams,
  elapsed: bigint,
  bound: bigint,
): [bigint, bigint] {
  const mid = midFromBalancesWad(balanceIn, balanceOut);
  const r = reservationPriceWad(mid, q, p, elapsed);
  const delta = halfSpreadWad(p, elapsed);

  const exposed = q >= 0n;

  let price = exposed ? r - delta : r + delta;
  if (price < 1n) price = 1n;

  let [newIn, newOut] = recenterBalances(balanceIn, balanceOut, price);

  if (exposed) {
    const penaltyBps = softBoundPenaltyBps(q, bound);
    if (penaltyBps !== 0n) {
      newOut -= (newOut * penaltyBps) / BPS;
    }
  }

  return [newIn, newOut];
}

/**
 * The effective price this call quotes, before the curve is rotated onto it.
 *
 * Not part of the on-chain surface — the instruction folds it straight into
 * {applyInventorySkew} — but it is the number a solver and the console want to
 * see, and it is what the subgraph publishes.
 */
export function effectivePriceWad(
  balanceIn: bigint,
  balanceOut: bigint,
  q: bigint,
  p: KernelParams,
  elapsed: bigint,
): bigint {
  const mid = midFromBalancesWad(balanceIn, balanceOut);
  const r = reservationPriceWad(mid, q, p, elapsed);
  const delta = halfSpreadWad(p, elapsed);
  const price = q >= 0n ? r - delta : r + delta;
  return price < 1n ? 1n : price;
}
